import os
import logging
import torch
from audiocraft.models import MusicGen
from audiocraft.data.audio import audio_write

# Set up logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

class MusicGenerator:
    def __init__(self, prompt, duration=30, output_dir="workspace"):
        """
        prompt: The exact text string generated by Phase 2.
        duration: Length of the video in seconds. 
        """
        self.prompt = prompt
        # Clamp duration to a maximum of 30 seconds since MusicGen small cannot generate longer continuously
        self.duration = min(duration, 30)
        self.output_dir = output_dir
        # AudioCraft automatically appends the .wav extension
        self.output_base_name = os.path.join(output_dir, "generated_bgm") 
        
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)
            
        # Automatically detect if a GPU is available to speed up generation
        self.device = "cuda" if torch.cuda.is_available() else "cpu"

    def generate_track(self):
        logging.info(f"Initializing MusicGen on {self.device.upper()}...")
        if self.device == "cpu":
            logging.warning("No GPU detected. Generation on CPU will be slow. Please be patient.")
            
        try:
            # We use 'facebook/musicgen-small' to prevent crashing consumer-grade PCs.
            # It only requires ~4GB of VRAM but still sounds incredibly good.
            model = MusicGen.get_pretrained('facebook/musicgen-small', device=self.device)
            
            # Set how long the generated audio should be (up to 30 seconds per generation pass)
            model.set_generation_params(duration=self.duration)
            
            logging.info(f"Generating {self.duration} seconds of audio for prompt: '{self.prompt}'")
            
            # The generation step (This is where the AI actually "composes" the audio)
            wav_tensor = model.generate([self.prompt]) 
            
            # Save the generated audio tensor to a file
            for idx, one_wav in enumerate(wav_tensor):
                # audio_write normalizes the audio and saves it as a standard wav file
                audio_write(
                    self.output_base_name, 
                    one_wav.cpu(), 
                    model.sample_rate, 
                    strategy="loudness", 
                    loudness_compressor=True
                )
            
            final_path = self.output_base_name + ".wav"
            logging.info(f"Music successfully generated and saved to {final_path}")
            return final_path

        except torch.cuda.OutOfMemoryError:
            logging.error("GPU Out of Memory (OOM)! The track duration is too long for your VRAM.")
            torch.cuda.empty_cache() # Free up stuck memory
            return None
        except Exception as e:
            logging.error(f"Music generation failed critically: {e}")
            return None

# Execution Block
if __name__ == "__main__":
    # Simulating data passed from Phase 2
    # In a real run, this comes directly from phase2_composer.py
    test_prompt = "110 BPM, cinematic background music, atmospheric, synth, bass"
    
    # We will set a short duration of 10 seconds just for testing the script
    test_duration = 10 
    
    generator = MusicGenerator(prompt=test_prompt, duration=test_duration)
    generated_file_path = generator.generate_track()
    
    print(f"\nPhase 3 Complete. Data to pass to Phase 4: {{'bg_music_path': '{generated_file_path}'}}")